export default {
    deadline: [{
        value: 'FourHour',
        label: '4小时内'
    }, {
        value: 'EightHour',
        label: '8小时内'
    }, {
        value: 'TwelveHour',
        label: '12小时内'
    }, {
        value: 'SixteenHour',
        label: '16小时内'
    }, {
        value: 'TwentyHour',
        label: '20小时内'
    }, {
        value: 'OneDay',
        label: '1天内'
    }, {
        value: 'TwoDay',
        label: '2天内'
    }, {
        value: 'ThreeDay',
        label: '3天内'
    }, {
        value: 'FiveDay',
        label: '5天内'
    }, {
        value: 'SevenDay',
        label: '7天内'
    }, {
        value: 'TenDay',
        label: '10天内'
    }, {
        value: 'TwelveDay',
        label: '12天内'
    }, {
        value: 'FifteenDay',
        label: '15天内'
    }, {
        value: 'EighteenDay',
        label: '18天内'
    }, {
        value: 'TwentyDay',
        label: '20天内'
    }, {
        value: 'TwentyFiveDay',
        label: '25天内'
    }, {
        value: 'ThirtyDay',
        label: '30天内'
    }, {
        value: 'ThirtyFiveDay',
        label: '35天内'
    }, {
        value: 'FortyFiveDay',
        label: '45天内'
    }]
}